// SPDX-License-Identifier: MIT
// Copyright (c) 2026 the TeraSharp contributors

// Native bucket3 QA help entries; Arb085:16122-16539. Generated from data/t201/native-commands.json.
namespace TeraSharp.Arbiter.Handlers;
public static class QaCommandHelpData
{
    public sealed record Entry(string Name, string Arguments, string Description);
    public static readonly Entry[] Rows =
    {
        new(@"connection",@"",@"동접"),
        new(@"usage",@"",@"IO관련 사용률"),
        new(@"dis",@"",@"그냥 client 연결 끊어버리기 테스트"),
        new(@"logout",@"",@"로그아웃 테스트"),
        new(@"profile",@"",@"프로파일링"),
        new(@"reset_profile",@"",@"리셋 프로파일데이타"),
        new(@"escape",@"캐릭명",@"어딘가로 이동"),
        new(@"check_simple_tip",@"simpleTipId",@"간단팁 본것으로 체크"),
        new(@"clear_simple_tip",@"",@"간단팁 체크 정보 초기화"),
        new(@"sticktogether",@"",@""),
        new(@"delete_all_parcels",@"",@"DB에서 모든 우편 정보를 삭제합니다.(서버 재시작 필요)"),
        new(@"sub_parcel_days",@"[days] [title]",@"제목이 @title인 모든 소포 전송 시점을 @days일 만큼 과거로 조작(서버 재시작 필요)"),
        new(@"parcelreturn",@"소포반송시간",@"소포반송시간"),
        new(@"char_record",@"캐릭터 녹화",@"캐릭터 녹화"),
        new(@"char_record_end",@"캐릭터 녹화 중지",@"캐릭터 녹화 중지"),
        new(@"sysconfig",@"[new config value]",@"시스템 설정 바꾸기"),
        new(@"ware_duration",@"[time in seconds]",@"창고 수수료 기간 조절"),
        new(@"clear_inven",@"",@"인벤토리 모두 비우기"),
        new(@"set_bypass",@"on/off",@"Bypass 껐다 켜기"),
        new(@"crash_arbiter",@"",@"아비터 크래시 시키기"),
        new(@"set_play_limit",@"제한수",@"대기열 생기도록 최대"),
        new(@"set_admin_level",@"캐릭명 레벨",@"디버그/어드민 커맨드를 위해서"),
        new(@"set_go",@"on/off",@"GO 캐릭터 설정"),
        new(@"refresh_inven",@"",@""),
        new(@"reg_party",@"",@"파티매치 등록"),
        new(@"unreg_party",@"",@"파티매치 삭제"),
        new(@"show_party",@"",@"파티매치 목록보기"),
        new(@"apply_party",@"",@"파티지원"),
        new(@"show_cand",@"",@"지원자 목록보기"),
        new(@"change_pr",@"",@"홍보문구 바꾸기"),
        new(@"set_logout_time",@"캐릭명 년 월 일",@"로그아웃 시간지정"),
        new(@"test_on",@"테스트종류, 기타인자",@"프로그램테스트 시작"),
        new(@"test_off",@"",@"프로그램테스트 종료"),
        new(@"ps_reg_window",@"",@"영주 후보 등록창 열기"),
        new(@"ps_vote_window",@"",@"영주 투표창 열기"),
        new(@"ps_com_window",@"[대륙번호] [0:투표 1:전장]",@"영주 경쟁창 보기"),
        new(@"ps_guard_window",@"",@"가드 정보창 열기"),
        new(@"ps_period_minute",@"[minute]",@"영주 선출 주기 분단위로 바꾸기"),
        new(@"ps_go_next",@"",@"영주 선출단계 강제로 다음으로"),
        new(@"ps_clear_election",@"",@"영주 및 선출정보 초기화"),
        new(@"ps_activate_election",@"",@"영주 시스템 활성화"),
        new(@"ps_add_point",@"[point]",@"경쟁포인트 추가"),
        new(@"ps_guard_info",@"[guardId]",@"가드정보 보기"),
        new(@"ps_policy_point",@"[point]",@"정책포인트 변경 / 영주만 가능"),
        new(@"ps_calc_tax",@"",@"세금 강제정산 / 영주만 가능"),
        new(@"ps_world_tick",@"[sec]",@"월드 틱 변경"),
        new(@"ps_im_king",@"[guardId]",@"영주즉위"),
        new(@"ps_vote_count",@"[count]",@"투표수 조작"),
        new(@"ps_maketax",@"[value]",@"세금 총액변경"),
        new(@"ps_planet_vote",@"on/off",@"전 서버 1계정 1투표"),
        new(@"reset_dungeon",@"",@"모든 인던 리셋"),
        new(@"set_trade_broker_remain_hours",@"",@"거래중개소 등록된 아이템 남은 만료시간 설정"),
        new(@"tb_avg_price",@"",@"거래중개소 평균 거래가 다시 계산"),
        new(@"set_tb_avg_price",@"[tid] [enchant] [masterpiece] [avgPrice]",@"거래중개소 특정 아이템 평균 거래가 셋팅"),
        new(@"clear_tb_avg_price",@"",@"거래중개소 평균 거래가 모두 초기화"),
        new(@"auto_recalc_tb_avg",@"[on/off]",@"거래중개소 평균 거래가 자동 계산 on/off"),
        new(@"set_escrow_return_wait",@"",@"에스크로우편 반송 대기 시간 설정"),
        new(@"set_max_recv_mail_cnt",@"",@"받은편지함 최대 갯수 설정"),
        new(@"set_max_send_mail_cnt",@"",@"보낸편지함 최대 갯수 설정"),
        new(@"testitem",@"[testItem]",@"TestItem"),
        new(@"set_chat_ban",@"[set_chat_ban]",@"set_chat_ban"),
        new(@"blocklist_max",@"[count]",@"차단가능한 유저 수 변경"),
        new(@"friendlist_max",@"[count]",@"친구등록가능한 유저 수 변경"),
        new(@"pchannel_max",@"[count]",@"개인채팅채널 입장 가능한 유저 수 변경"),
        new(@"warehousegold_max",@"[amount]",@"100 은 창고에 100원까지 보관 가능 0 은 원래대로"),
        new(@"Guildaddmax",@"[amount]",@"100 은 길드 가입최대 인원이 100명까지 0 은 원래대로"),
        new(@"set_dungeoncool",@"[dungeonId] [minutes]",@"던전 쿨타임 설정"),
        new(@"phaselevel",@"[continentId] [phaseLevel]",@"던전 페이즈 레벨 설정"),
        new(@"reset_all_phaselevel",@"모든 유저 던전 페이즈 레벨 초기화 (아비터)",@""),
        new(@"set_guild_rec",@"",@"길드 추천수 조절"),
        new(@"import_characters",@"",@""),
        new(@"BOT_recvmsg",@"",@""),
        new(@"BOT_check",@"",@""),
        new(@"masterpiece",@"",@""),
        new(@"makeitem_mprate",@"[명품 배율]",@"makeItem 명령어 사용시 명품 배율 고정"),
        new(@"reserve_festival",@"[EventId] [StartTime] [EndTime]",@"월드 이벤트 예약"),
        new(@"start_festival",@"[EventId]",@"월드 이벤트 시작"),
        new(@"stop_festival",@"[EventId]",@"월드 이벤트 종료"),
        new(@"set_pcbang",@"[on/off]",@"pc방 유저인지 설정"),
        new(@"set_new_member",@"[on/off]",@"신규 유저인지 설정"),
        new(@"reset_admin_reward",@"",@"어드민 보상 기록 초기화"),
        new(@"turn_netm",@"[on|off]",@"Net Moderator 켜고 끄기"),
        new(@"reload_netm",@"",@"NetModeratorConfig.xml Reload"),
        new(@"turn_ir",@"[on|off]",@"Input Restriction 켜고 끄기"),
        new(@"reload_ir",@"",@"InputRestrictionData.xml Reload"),
        new(@"clear_serverachievement",@"[id]",@"서버최초 업적 초기화"),
        new(@"clear_all_serverachievement",@"",@"전체 서버최초 업적 초기화"),
        new(@"set_account_res_level",@"[level]",@"제한계정 레벨 세팅"),
        new(@"nexus_bypass",@"",@""),
        new(@"nexus_broadcast",@"",@""),
        new(@"world_of_party_match",@"",@""),
        new(@"tutorial",@"on/off",@"튜토리얼 플레이"),
        new(@"tutorialPlayer",@"on/off",@"튜토리얼 플레이가 필요한 녀석인지 강제 세팅"),
        new(@"reset_event_mail",@"[이벤트ID]",@"이벤트메일 리셋"),
        new(@"pk_section",@"[area id] [section id] [on/off]",@"Section 별 Pk OnOff"),
        new(@"huntingevent_add",@"[type] [hz] [val] [duration]",@"사냥터 이벤트 추가"),
        new(@"huntingevent_remove",@"[event id]",@"사냥터 이벤트 제거"),
        new(@"publisher",@"[publisher name]",@"퍼블리셔 변경"),
        new(@"dungeon_log",@"[on/off]",@"던전 로그 사용 설정"),
        new(@"rank_next_season",@"[dungeonId id]",@"기록 경쟁 해당 던전 시즌 넘김"),
        new(@"rank_sort",@"",@"기록 경쟁 순위 바로 계산"),
        new(@"chrono_debug",@"[mode]",@"크로노스크롤 디버그 모드"),
        new(@"dailyevent",@"[dayOfWeek]",@"요일이벤트 날짜 변경(0:없음 1:일 2:월 ... 7:토)"),
        new(@"clear_bf_cool",@"",@"전장 쿨타임 및 입장 횟수 모두 삭제"),
        new(@"observer_mode",@"[on/off]",@"관전 모드 활성화/비활성화"),
        new(@"set_bf_result",@"[전장ID] [승] [무] [패] [개인평점]",@""),
        new(@"reset_bf_result",@"",@"전장 평점 초기화"),
        new(@"get_bf_result_resettime",@"",@"마지막으로 진행한 평점 초기화 시간 알아내기"),
        new(@"ps_candidacy_membercount",@"[member-count]",@"후보자 등록 필수 길드 회원수 조정"),
        new(@"create_guild",@"[guild-name] [first-username]",@"새로운 길드를 생성"),
        new(@"create_user",@"[username]",@"새로운 캐릭터를 생성"),
        new(@"lord_behavior",@"[behavior-type-id]",@"영주 업적 행동 테스트 메시지 송신"),
        new(@"toggle_guildwar_acceptable",@"",@"길드전 허용 상태 토글"),
        new(@"reset_guildwar_toggle_cool",@"",@"길드전 허용 상태 토글 쿨타임 초기화"),
        new(@"guildwar_immediate",@"",@"진행 대기중인 모든 길드전 즉시 시작"),
        new(@"ps_gw_reset",@"",@"영주길드전 경쟁 포인트 습득 제한 초기화"),
        new(@"ps_gw_time",@"[Hour]",@"영주길드전 경쟁 포인트 습득 제한 초기화 시간 변경"),
        new(@"ps_gw_point",@"[Point]",@"영주길드전 경쟁 포인트 변경"),
        new(@"set_referer",@"[RefererName] [RefereeName]",@"Refer-A-Friend 초대자 설정"),
        new(@"create_many_guilds",@"[count:1~99]",@"길드 많이 만들기(기본 길드가입 조건 부여)"),
        new(@"create_many_guilds_random_condition",@"[count:1~99]",@"길드 많이 만들기(길드가입 조건 랜덤부여)"),
        new(@"create_many_guilds_and_users",@"[guild count:1~99] [user count:2~60]",@"길드 많이 만들고(길드가입 조건 랜덤부여) 유저수도 랜덤하게 하기"),
        new(@"create_many_guilds_for_invite_user_to_guild",@"[count:1~20]",@"(많은)길드를 만들어서 나에게 길드초대를 보내도록 함"),
        new(@"create_many_users_for_guild_wanted_writing",@"[count:1~20]",@"(많은)유저를 만들어서 길드구함 글을 등록하도록 함"),
        new(@"create_many_users_and_apply_guild",@"[count:1~20]",@"(많은)유저를 만들어서 길드에 가입신청을 하도록 함"),
        new(@"create_many_users_to_my_guild",@"[count:1~50]",@"내 길드에 많은 유저 가입시키기"),
        new(@"create_many_users_to_my_account",@"[count]",@"내 계정 내 유저 많이 만들기"),
        new(@"clear_vote_cool",@"",@"투표 쿨타임 모두 삭제"),
        new(@"set_guild_play_time_next_week",@"",@"playtime에 대해 계산하는 로직을 한 주 넘김(길드검색 시 활용)"),
        new(@"add_guild_this_week_play_time",@"[guildName] [addTime(unit:sec)]",@"특정 길드에 thisweekplaytime 추가"),
        new(@"show_guild_week_play_time",@"[guildName]",@"특정 길드의 weekplaytime을 보여주도록 함"),
        new(@"init_guild_wanted_writing_rewrite_time",@"",@"길드구함 재등록시간 없애기"),
        new(@"change_guild_member_count",@"[길드이름] [변경할 길드원 수]",@"특정 길드의 길드원 수 조절"),
        new(@"clear_wanted_writing",@"",@"길드구해요 시스템 완전초기화(각 쿨타임까지)"),
        new(@"join_guild",@"[guildName]",@"길드에 가입하기"),
        new(@"unlock_all_movies",@"",@"모든 영상을 unlock 합니다"),
        new(@"set_arbiter_worldparam",@"[param-name] [param-value]",@"WorldParam 수정"),
        new(@"add_package",@"[PackageId] [ExpireSecond] {[UserName]}",@"Account Trait Package 설정"),
        new(@"remove_package",@"[PackageId] {[UserName]}",@"Account Trait Package 설정"),
        new(@"clear_package",@"{[UserName]}",@"Account Trait Package 초기화"),
        new(@"init_awesomium",@"",@"Awesomium 초기화"),
        new(@"open_awesomium",@"[URL]",@"Awesomium dialog open & navigate"),
        new(@"set_awesomium_web_url",@"[url]",@"awesomium URL 설정"),
        new(@"set_awesomium_debug_mode",@"[on/off]",@"awesomium DebugMode 설정"),
        new(@"query_point",@"",@"Cash point 조회"),
        new(@"purchase_prod",@"[ProductID]",@"상품 구매"),
        new(@"create_bill_account",@"",@"구좌 생성"),
        new(@"fund_coin",@"[Funding acmount]",@"현금 충전"),
        new(@"reload_shop_data",@"",@"Reload shop data"),
        new(@"change_shop_status",@"",@"change shop status"),
        new(@"init_limited_gacha",@" [gachaId]",@"init LimitedGacha"),
        new(@"limited_gacha_go_next_bucket",@"[gachaId] [1/0]",@"go next bucket"),
        new(@"clear_parcel",@" [캐릭터 이름] ",@"대상 캐릭터의 소포 비우기"),
        new(@"clear_recipe",@"",@"RECIPE 비우기"),
        new(@"change_loading_screen_status",@"[Loading Screen Control Status]",@"Loading Screen Control"),
        new(@"write_board",@"",@"등산 게시판 글쓰기 [id] [내용] [개수]"),
        new(@"clear_board",@"",@"등산 게시판 글쓰기 [id] [내용] [개수]"),
        new(@"set_board_clear_time",@"",@"등산게시판 작성횟수 리셋 시간 설정 [시간/분]"),
        new(@"guild_join_cooltime",@"",@"길드 재가입 쿨타임 설정 "),
        new(@"party",@"[userName]",@"파티 만들기"),
        new(@"battlefield",@"[battleFieldId other-username]",@"전장 진입"),
        new(@"raid",@"[레이드 인원]",@"레이드 파티 구성"),
        new(@"send_mass_parcel",@"",@"나에게 대규모 우편 보내기 테스트용"),
        new(@"testautomation_clear_allusers_completely",@"",@"테스트자동화용 - 현재 Account의 모든 유저들을 완전히 삭제 (복구불가)"),
        new(@"dbg_break",@"",@"debug - 강제로 Break Point Exception 발생"),
        new(@"change_voice",@"",@""),
        new(@"versionInfoHide",@"",@""),
        new(@"insert_floating_castle_parts",@"파츠Id",@"파츠인벤에 파츠 추가"),
        new(@"assign_floating_castle",@"부유성 아이디",@"부유성 지급"),
        new(@"collect_floating_castle",@"부유성 아이디",@"부유성 회수"),
        new(@"set_floating_castle_coin",@"추가 포인트",@"파츠 상점 코인 추가"),
        new(@"reset_floating_castle_parts_cooltime",@"부유성 파츠 쿨타임 리셋",@"부유성 파츠 쿨타임 리셋"),
        new(@"assign_guild_emblem",@"엠블렘 Type, 엠블렘 Id",@"길드 엠블렘 부여"),
        new(@"collect_guild_emblem",@"엠블렘 Type, 엠블렘 Id",@"길드 엠블렘 부여"),
        new(@"clear_friend_request",@"",@"친구 신청 제한 초기화"),
        new(@"change_achievement_season",@"[시즌ID]",@"업적 시즌 변경"),
        new(@"clear_achievement_season",@"",@"업적 시즌 DB 초기화 (서버 재시작 필요)"),
        new(@"reset_charsock",@"",@"캐릭터 소켓 확장 초기화"),
        new(@"reset_ware",@"",@"창고 초기화"),
        new(@"reset_ware_slot",@"",@"창고 슬롯 확장 초기화"),
        new(@"reset_styleware",@"",@"스타일 창고 슬롯 확장 초기화"),
        new(@"add_friend",@"[userName]",@"친구 추가"),
        new(@"add_many_friends",@"[count (1~50)]",@"여러명의 유저 생성해서 친구 추가하기"),
        new(@"delete_friend",@"[userName]",@"친구 삭제"),
        new(@"add_friendship",@"[userName] [point]",@"해당 친구에 대한 친분도 증가"),
        new(@"add_friendship_party",@"[point]",@"파티원 중 친구에게 친분도 추가"),
        new(@"delete_friend_limit_off",@"",@"친구 삭제 무제한으로 설정"),
        new(@"consoleprint_commandlist",@"",@"모든 어드민 커맨드 리스트 ConsoleLog 출력"),
        new(@"help",@"[keyword]",@"QA 명령어 검색"),
        new(@"show_friendship_info",@"[on/off]",@"친분도 획득사유 및 점수 시스템메시지 출력"),
        new(@"reset_invitecode",@"",@"인게임 초대코드 사용횟수 초기화"),
        new(@"set_returnuser",@"",@"처음 복귀한 유저로(복귀고객 가이드 전용) 설정 ( 재접속 필요 )"),
        new(@"reset_returnuser",@"",@"처음 복귀한 유저로(복귀고객 가이드 전용) 설정 ( 재접속 필요 )"),
        new(@"qatest",@"on/off",@""),
        new(@"use_style_warehouse",@"on/off (생략:on)",@"스타일 창고 사용 여부"),
        new(@"add_item_period",@"[itemTemplateId] [eventStartTime] [eventEndTime] [itemPeriodTime]",@"기간제 아이템 정보 추가"),
        new(@"delete_item_period",@"[itemTemplateId]",@"기간제 아이템 정보 삭제"),
        new(@"clear_all_item_period",@"",@"기간제 아이템 정보 일괄 삭제"),
        new(@"change_date",@"[date]",@"서버 날짜 변경"),
        new(@"change_time",@"[time]",@"서버 시간 변경"),
        new(@"string",@"[스트링 이름] [스트링 아이디]",@"스트링 표시"),
        new(@"info_dungeon",@"",@"[기본정보]>[인던]의 출력내용 표시"),
        new(@"reset_attendance_event_reward",@"",@"출석체크 이벤트 보상 받았던 정보 초기화"),
        new(@"clear_level_reward",@"레벨 이벤트 보상 받는 기록 삭제",@""),
        new(@"reload_datasheet",@"",@"데이트 시트 리로드"),
        new(@"clientCommand",@"[Args..]",@"클라이언트 명령어(QA)"),
        new(@"cc",@"[Args..]",@"클라이언트 명령어(QA)"),
        new(@"setplaytime",@"[일간누적(분)] [총누적(분)]",@"PC방 접속시간 프로모션 접속시간 설정"),
        new(@"getplaytime",@"",@"PC방 접속시간 프로모션 접속시간 알려줌"),
        new(@"resetplaytimereward",@"",@"PC방 접속시간 프로모션 보상 리셋"),
        new(@"set_vip_level",@"[level]",@"Vip 시스템 등급 조정"),
        new(@"add_vip_game_exp",@"[exp]",@"Vip 시스템 게임 경험치 획득"),
        new(@"add_vip_pub_exp",@"[exp]",@"Vip 시스템 퍼블리셔 경험치 획득"),
        new(@"gara_pub_exp",@"[on/off]",@"인게임상점을 통해 가짜로 퍼블리셔 경험치 획득"),
        new(@"add_vip_token",@"개수",@"Vip Token 늘리기"),
        new(@"clear_vip_token_recv",@"",@"Vip Token 획득 정보 리셋"),
        new(@"clear_vip_reward_recv",@"",@"Vip 보상 받은 정보 리셋"),
        new(@"viptest",@"[on/off]",@"Client 자체 Vip Test 명령어 on/off"),
        new(@"addstyleshop",@"[itemTid] or [itemTid] [saleStart] [saleEnd] [previewStart] [previewString] [price]",@"스타일샵 판매 아이템 추가"),
        new(@"addawakenchange",@"[scrollTID] [scrollCount] [materialCount]",@"각성변환 데이터 추가(1일)"),
        new(@"addawakenenchant",@"[scrollTID] [scrollCount] [materialCount] [enchantStep] [combatRank] [combatType(1,3,4,5)]",@"각성강화 데이터 추가(1일)"),
        new(@"deleteawakenchange",@"[eventId]",@"각성변환 데이터 삭제"),
        new(@"deleteawakenenchant",@"[eventId]",@"각성강화 데이터 삭제"),
        new(@"del_city_war_rank",@"[leagueId][SeasonId][guildDbId]",@"랭킹 삭제"),
        new(@"chnage_city_war_interestOnly",@"[leagueId][on/off]",@"관계자 입장 설정 기능"),
        new(@"set_city_war_open_time",@"[leagueId][day][hour][playTime]",@"공방전 오픈 시간 변경"),
        new(@"add_city_war_guild_ban",@"[leagueId][guildDbId]",@"공방전 길드 벤 리스트 추가"),
        new(@"del_city_war_guild_ban",@"[leagueId][guildDbId]",@"공방전 길드 벤 리스트 추가"),
        new(@"add_citywar_taxpot",@"[taxId][taxMoney]",@"세금 추가"),
        new(@"set_tax_config",@"[taxId][tradeTax][storeTax][payRate][serverAdjust]",@"세율 설정"),
        new(@"guild_cooltime",@"on/off",@"길드 가입 쿨타임 OnOff"),
        new(@"guild_level",@"[level]",@"레벨 변경"),
        new(@"add_guild_point",@"[point]",@"포인트 획득"),
        new(@"add_guild_money",@"[coin]",@"길드 자금 획득"),
        new(@"add_guild_exp",@"[exp]",@"길드 경험치 획득"),
        new(@"reset_weekly_contribution_point",@"",@"주간 길드 기여도 초기화"),
        new(@"add_guild_contribution_point",@"[point]",@"길드 기여도 획득 (주간 상환은 넘을 수 없다)"),
        new(@"calc_guild_level_ranking",@"",@"길드 레벨 순위 현황 재계산"),
        new(@"refresh_quest_cache",@"",@"퀘스트 다시 불러오기"),
        new(@"guild_quest_start",@"[questTemplateId]",@"길드 퀘스트 시작"),
        new(@"guild_quest_complete",@"[questTemplateId]",@"길드 퀘스트 완료"),
        new(@"guild_quest_clear",@"[questTemplateId]",@"길드 퀘스트 진행정보 삭제"),
        new(@"add_guild_quest",@"[questTemplateId]",@"수행 가능 목록에 길드 퀘스트 추가"),
        new(@"guild_quest_add_limit_time",@"[addMin]",@"진행중인 길드 퀘스트의 남은 제한 시간 증감"),
        new(@"reset_guild_quest",@"",@"일간 할당량과 길드 임무 리스트를 새로 갱신"),
        new(@"give_guild_incentive",@"[incentiveRate]",@"길드 포상금을 우편으로 지급"),
        new(@"guildwar_declare",@"[길드명]",@"길드전 선포"),
        new(@"guildwar_cancel",@"[길드명]",@"길드전 선포 철회"),
        new(@"guildwar_surrender",@"[길드명]",@"길드전 항복"),
        new(@"guildwar_cooltime",@"[minute]",@"선포,철회,항복 쿨타임 적용"),
        new(@"load_gmevent",@"",@"GM이벤트 데이터시트 로드"),
        new(@"gmevent_change_maxjoincount",@"",@"GM이벤트 하루 최대참여횟수 변경"),
        new(@"gmevent_notice",@"[공지내용]",@"GM이벤트 운영자 공지"),
        new(@"load_saevent",@"",@"데이터시트에 정의된 테스트용 누적출석이벤트 추가"),
        new(@"clear_saevent",@"",@"누적출석이벤트 모두 삭제"),
        new(@"resettime_saevent",@"",@"reset시간을 현재 시각으로 갱신"),
        new(@"add_event_system",@"[조건최소레벨][조건최대레벨][조건클래스][이벤트타입][TargetTemplateId][달성횟수]",@"이벤트 시스템 이벤트 추가"),
        new(@"delete_all_event_system",@"",@"이벤트 시스템 이벤트 모두 제거"),
        new(@"add_namepreempt_event",@"[이벤트 클래스][시간간격]",@"닉네임 선점 이벤트 추가"),
        new(@"skill_cheater_arbiter",@"[on/off] [termSeconds(int)] [countThreashold(int)] [kick/nokick]",@"스킬 치터 설정변경"),
        new(@"toggle_onoff",@"[id] [on/off]",@"컨텐츠 on/off 토글"),
        new(@"open_identify",@"[on/off]",@"아이템 생성시 무조건 봉인해제"),
        new(@"makeuser_pvprank",@"[UserCount:1~100][BattleFieldId]",@"유저생성 후 전장 랭킹 등록"),
        new(@"makeuser_pverank",@"[ContinentId][StageLevel][UserCount:1~100]",@"유저생성 후 던전 랭킹 등록"),
        new(@"update_bf_score",@"[battleFieldId][gradeScore]",@"현재 전장 점수 세팅"),
        new(@"update_pverank",@"[continentId][level][time(ms)]",@"현재 던전 기록 세팅"),
        new(@"clear_pverank",@"[continentId]",@"해당 던전의 시즌 기록 모두 제거"),
        new(@"clear_pverank_player",@"[continentId]",@"자신의 해당 던전 기록 제거"),
        new(@"init_battlefield_season",@"",@"전장 시즌 초기화"),
        new(@"init_dungeon_season",@"",@"던전 시즌 초기화"),
        new(@"clear_all_pvprank",@"",@"PVP 전장 기록, 랭킹 모두 초기화"),
        new(@"clear_all_pverank",@"",@"PVE 던전 기록, 랭킹 모두 초기화"),
        new(@"set_bf_result_resettime",@"[yyyy] [mm] [dd] [h]",@"마지막 전장 랭킹 초기화 시간 설정하기 (utc로 입력할 것)"),
        new(@"set_dg_result_resettime",@"[yyyy] [mm] [dd] [h]",@"마지막 던전 랭킹 초기화 시간 설정하기 (utc로 입력할 것)"),
        new(@"start_rookie_event",@"[continentId] [hour] [rewardItem] [amount]",@"멘토링 이벤트 시작(시간은 현재로부터 더해져 종료시간이 설정됨)"),
        new(@"add_dungeon_abnormality",@"[continentId] [abnormalId] [startTime] [endTime]",@"던전 이상상태 이벤트 추가하기"),
        new(@"reset_buymenu",@"",@"상점 구매 제한 초기화(월드 단위)"),
        new(@"reset_buymenu_limit",@"",@"상점 구매 제한 초기화(월드 단위)"),
        new(@"store_changeinfo_arbiter",@"[index]",@"상점 아이템 판매 수정 사항 보여주기 (ArbiterServer)"),
        new(@"store_changeinfo_add",@"random [amount] (buylist/buylistrange) [listid...] (item/itemrange) [templateId...]",@"상점 아이템 수정 사항 추가하기"),
        new(@"reset_premium_slot",@"",@"프리미엄 슬롯 리셋"),
        new(@"check_premium_slot_reset_time",@"",@"프리미엄 슬롯 리셋 시간 확인"),
        new(@"send_mass_parcel_n",@"",@"나에게 우편 보내기 테스트용(n: 숫자지정)"),
        new(@"reset_card_collection",@"",@"카드 도감 초기화"),
        new(@"card_collection_level",@"[level]",@"카드 도감 레벨 변경"),
        new(@"perfect_card_collection",@"",@"전체 카드 수집"),
        new(@"add_card_collection_point",@"[point]",@"카드 도감 점수 추가"),
        new(@"set_card_preset_amount",@"[point]",@"카드 프리셋 수 조절"),
        new(@"increase_guild_reward_point",@"[point]",@"길드임무 포인트 업데이트"),
        new(@"guild_quest_usable",@"[on/off]",@"길드 임무 이용가능 on/off, 길드 가입일을 수정함"),
        new(@"reset_guild_reward",@"",@"길드 보상 포인트와 길드 보상 히스토리 초기화"),
        new(@"show_timeline_dungeon",@"[대륙ID]",@"던전 타임라인 확인"),
        new(@"add_timeline_dungeon",@"[대륙ID] [요일] [HHMM] [HHMM]",@"던전 타임라인 추가"),
        new(@"reset_timeline_dungeon",@"",@"던전 타임라인 초기화"),
        new(@"show_timeline_eventmatching",@"[지령서ID]",@"지령서 타임라인 확인"),
        new(@"add_timeline_eventmatching",@"[지령서ID] [요일] [HHMM]",@"지령서 타임라인 추가"),
        new(@"reset_timeline_eventmatching",@"",@"지령서 타임라인 초기화"),
        new(@"change_deco_ui",@"[decoUIId]",@"데코 ui 변경"),
        new(@"sim_match_progress",@"[tankerCount] [dealerCount] [healerCount]",@"매칭 현황 UI 테스트"),
        new(@"dungeon_onoff",@"[dungeonId] [on/off]",@"던전 On/Off"),
        new(@"perfect_hero",@"",@"TBA 모든 영웅 ,스킨 획득"),
        new(@"reset_hero",@"",@"TBA 영웅 ,스킨 초기화"),
        new(@"perfect_rune",@"",@"TBA 모든 룬 획득, 룬 페이지 개방"),
        new(@"reset_rune",@"",@"TBA 보유 룬, 룬페이지 초기화"),
        new(@"delete_tbauser",@"",@"TBA 유저 삭제"),
        new(@"force_start_battlepass_season",@"[seasonId]",@"배틀패스 시즌 시작"),
        new(@"force_end_battlepass_season",@"",@"배틀패스 시즌 종료"),
        new(@"check_battlepass_season",@"",@"배틀패스 시즌 확인"),
        new(@"reset_battlepass_data",@"",@"배틀패스 시즌 데이터 초기화"),
        new(@"change_hero_rotation",@"[rotationId]",@"TBA 영웅 로테이션 변경"),
        new(@"get_hero_rotation_time",@"",@"TBA 영웅 로테이션 날짜 출력"),
        new(@"add_tba_currency",@"[buyPriceType(1: TCat, 2: TBAFragment)] [amount]",@"TBA 전용 재화 추가"),
        new(@"tba_change_point",@"[target point]",@"TBA 랭킹 포인트 변경"),
        new(@"request_shop_url",@"",@""),
        new(@"add_tba_season",@"현재 시즌 삭제 후 새시즌 입력",@""),
    };
}
