// SPDX-License-Identifier: MIT
// Copyright (c) 2026 the TeraSharp contributors

namespace TeraSharp.Arbiter.Handlers;

// =============================================================================================
// WorldQaCommandData - T233. WorldServer's own QA command table, extracted from the binary.
//
// These do NOT run here. The Arbiter forwards an unknown /@ command to World, and World's
// CommandDistributor::ProcessCommand looks the name up in this registry - logging
// "QA Command: %s" when it resolves and, via WorldCommandDistributor::OnUnregisteredCommand,
// "[QA] Invalid Command: %s" plus "Invalid QA Command" to the caller when it does not. The list
// is here so /@help can answer for World too: T201 forwarded "_helpworld <term>" for that, and
// _helpworld is NOT one of the 545 names below - it does not exist on this build, so the
// forward could only ever have produced "Invalid QA Command".
//
// Provenance: every FUN_140114090(registry, type, name, handler, flag, args, usage) call in
// world_decompiled/WorldServer.exe.c - 545 of them. The decompile declares the data symbols as
// bare "undefined DAT_...", so 7 names, 231 argument strings and 48 usage strings were read out
// of Executable/WorldServer.exe directly (image base 0x140000000, RVA via the section table,
// UTF-16LE). An empty Arguments means the registration passed &PTR_1419c2970, whose target is
// eight zero bytes - the "no arguments" sentinel, not a string we failed to resolve.
//
// Usage text is retail's own, in Korean, verbatim. It is the ground truth; any English in
// status/WORLD-QA-COMMANDS.md is a gloss and is marked as ours there.
//
// Type is WorldServer's CommandType argument. OnUnregisteredCommand labels type 0 "OP" and
// everything else "QA"; the registry only ever uses 1 (15 commands - the battlefield and cheat
// set) and 4 (530 - the bulk QA set). "bookmark" is registered under both.
// =============================================================================================
public static class WorldQaCommandData
{
    /// <summary>One WorldServer registration. Arguments empty = the no-argument sentinel.</summary>
    public sealed record Entry(string Name, int Type, string Arguments, string Description);

    /// <summary>All 545 registrations, by name then type.</summary>
    public static readonly Entry[] Rows =
    {
        new(@"abnormality",4,@"이상상태아이디",@"이상상태 강제"),
        new(@"abnormality_off",4,@"이상상태아이디",@"이상상태 강제"),
        new(@"abnormality_show",4,@"이상상태아이디",@"이상상태 강제"),
        new(@"abnormality_time",4,@"[이상상태Id] [duration]",@"duration 지정해서 이상상태 강제"),
        new(@"accept_revival",4,@"",@"부활 받았을 경우 부활"),
        new(@"accomplish_achievement_rate",4,@"",@"현재 시즌 달성률 넘을 때까지 업적 달성시키기"),
        new(@"add_actpoint",4,@"[actPoint값]",@"모험의 주화 변경"),
        new(@"add_battlecoin",4,@"[금화수량]",@"신규모드 전장 내 금화 획득"),
        new(@"add_battlepass_exp",4,@"[Amount]",@"배틀패스 경험치 획득"),
        new(@"add_battlepass_token",4,@"[Amount]",@"배틀패스 토큰 획득"),
        new(@"add_bf_score",4,@"",@"전장 거점 점령점수 가산 [점수]"),
        new(@"add_daily_clear_count",4,@"[addBonusCount]",@"발키온 지령서 일일 보너스 퀘스트 완료 횟수 증가"),
        new(@"add_epexp",4,@"[exp]",@"EP Exp 변경"),
        new(@"add_exp",4,@"[EXP값]",@"경험치 더하기"),
        new(@"add_hp",4,@"[HP값]",@"HP 값 조정"),
        new(@"add_mat_enchant",4,@"[templateId] [enchantStep] [multiplier] ",@"재료 강화 아이템의 재료 획득"),
        new(@"add_mat_upgrade",4,@"[templateId] [enchantStep] [masterpiece] [awakened] [multiplier]",@"장비 승급 아이템의 재료 획득"),
        new(@"add_maxactpoint",4,@"[maxActPoint값]",@"모험의 주화 max값 변경"),
        new(@"add_mp",4,@"[MP값]",@"MP 값 조정"),
        new(@"add_npcguild",4,@"[npcGuildId]",@"평판 세력 등장"),
        new(@"add_partner",4,@"[파트너등록증templateId]",@"파트너 생성 후 소환"),
        new(@"add_partner_grade",4,@"",@"[버프 등급]"),
        new(@"add_partner_level",4,@"",@"[레벨]"),
        new(@"add_pet_exp",4,@"",@"[경험치]"),
        new(@"add_pet_level",4,@"",@"[레벨]"),
        new(@"add_route_epexp",4,@"[route] [exp]",@"특성 경험치 획득루트 지정해서 변경"),
        new(@"add_servant_ad_time",4,@"[필드 아이디] [더할 시간(분)]",@"서번트 모험 시간 변경"),
        new(@"add_servant_energy",4,@"[얼만큼]",@"펫 에너지 증감"),
        new(@"add_skill_polishing_exp",4,@"[exp]",@"skill polishing exp 변경"),
        new(@"add_st",4,@"[ST값]",@"ST 값 조정"),
        new(@"addpoint_gmevent",4,@"point",@"GM이벤트 추가"),
        new(@"adjust_bonfire",4,@"[시간]",@"유저가 만든 모닥불 남은 시간 변경"),
        new(@"aibehavior",4,@"[on 거리] or [off]",@"주위 Npc의 Ai 정보를 수집"),
        new(@"aiskill",4,@"[on 거리] or [off]",@"주위 Npc의 스킬 정보를 수집"),
        new(@"allabnormality",4,@"[on/off]",@"스킬에 의해 발생하는 이상상태 무조건 적용"),
        new(@"allhit",4,@"[on/off]",@"스킬 적관계 무시하고 무조건 적중"),
        new(@"allow_teleport",4,@"on/off",@"텔레포트 제한구역에서의 텔레포트 허용 여부"),
        new(@"allreaction",4,@"[0/1/2]",@"스킬 적중시 무조건 리액션 발생 (0없음, 1미니, 2기본)"),
        new(@"angry",4,@"[range]",@"분노모드로 바꾸기"),
        new(@"aoi",4,@"",@"주위 world object 개수"),
        new(@"apm_add",4,@"[id]",@"자동 파티 매칭 풀 진입"),
        new(@"apm_ask",4,@"",@"자동 파티 매칭 허용 팝업 띄움"),
        new(@"apm_reset",4,@"",@"자동 파티 매칭 허용 상태 초기화"),
        new(@"apm_use",4,@"[on/off]",@"자동 파티 매칭 사용 모드 변경"),
        new(@"assert",4,@"",@"어서트정보 테스트"),
        new(@"atk_speed",4,@"[공속비율]",@"비율대로 모든 스킬의 속도가 증가"),
        new(@"attendance",4,@"[YYYY] [MM] [DD]",@"해당 날짜에 출석체크"),
        new(@"autorevivaltime",4,@"[분]",@"자동 부활 시간 조절하기"),
        new(@"ban_guild",4,@"캐릭명",@"길드원 추방"),
        new(@"bf_chat",1,@"",@""),
        new(@"bf_end",1,@"",@""),
        new(@"bf_goto",1,@"",@""),
        new(@"bf_Invite",1,@"",@""),
        new(@"bf_kick",1,@"",@""),
        new(@"bf_leave",1,@"",@""),
        new(@"bf_match",1,@"",@""),
        new(@"block_load_topo_progress",4,@"[max_percent]",@"신규모드 진입할 때 topo 로딩이 이루어지고 있지 않은 것으로 간주"),
        new(@"block_quest",4,@"[questId]",@"퀘스트를 시작할 수 없게 막기"),
        new(@"bookmark",1,@"",@""),
        new(@"bookmark",4,@"bookmark_id",@"북마크(서버)"),
        new(@"box_prob",4,@"tid",@"가차 아이템 확률 정보 보기"),
        new(@"breakshield",4,@"[skillId]",@""),
        new(@"buy_styleshop_item",4,@"[itemTid]",@"스타일샵 아이템 구매 (TeraPuppet 이용 추천)"),
        new(@"calc_battle_field_ranking_next_time",4,@"",@"다음 번 서버 시작시 전장 랭킹 생성"),
        new(@"calc_battle_field_Season_next_time",4,@"",@"다음 번 서버 시작시 전장 시즌 생성"),
        new(@"calmdown",4,@"[range]",@"분노모드 해제"),
        new(@"cancelaction",4,@"[다음 액션번호]",@"액션 강제 해제"),
        new(@"card_collection_max_cost",4,@"[maxCost]",@"카드 도감 최대 코스트 설정"),
        new(@"change_battlepass_level",4,@"[Level]",@"배틀패스 레벨 변경"),
        new(@"change_daily_quest_record_reset_hour",4,@"[id]",@"일퀘 클리어 시간 변경"),
        new(@"change_daily_quest_seed_reset_hour",4,@"[id]",@"일퀘 시드 재생성 시간 변경"),
        new(@"change_epresettime",4,@"changeResetDay",@"EpReset 날짜 변경"),
        new(@"change_eventgage",4,@"[eventName] [value:0 ~ max]",@"던전 이벤트게이지 값 변경"),
        new(@"change_exp_gain_data",4,@"[on/off] or [level, ratio, on/off]",@"월드 경험치 획득량 조절 명령어"),
        new(@"change_guildchief",4,@"캐릭명",@"길드장 위임"),
        new(@"change_interval_event_system_playtime",4,@"[incSeconds]",@"누적플레이타임 증가 인터벌 변경 (60: 1시간, 1: 1분)"),
        new(@"change_npc_ai",4,@"[range] [huntingZoneId] [npcid] [patternListId]",@"NpcAi 조정하기"),
        new(@"change_npc_stat",4,@"[range] [ratio] [type]",@"NpcStat 비율 조정하기"),
        new(@"change_npc_to_user",4,@"",@"유저 변신모드 해제"),
        new(@"change_tba_time_attack",4,@"[남은시간]",@"신규모드 전장 내 남은 시간 변경"),
        new(@"change_user",4,@"[CLASS] [RACE] [GENDER]",@"클래스 종족 성별 바꾸기"),
        new(@"change_user_status",4,@"[battle/peace]",@"평화/전투 상태 변경"),
        new(@"change_user_to_npc",4,@"[huntingZoneId] [templateId]",@"유저 변신모드"),
        new(@"change_worldspawn_lifetime",4,@"[WorldSpawnId] [SpawnTerritoryGroupId] [lifeTime]",@"WorldSpawnData.xml에서 id가 WorldSpawnId인 WorldSpawn의 하위 노드 중 id가 SpawnTerritoryGroupId인 SpawnTerritoryGroup에 속한 SpawnTerritory들의 lifeTime을 수정한다."),
        new(@"changefatiguepoint",4,@"",@"생산력 강제 셋팅"),
        new(@"changenpc",4,@"[사냥터id] [NpcInstanceId]",@"Npc 교체 스폰"),
        new(@"changenpcangermode",4,@"[on/off]",@"분노모드 on/off"),
        new(@"charin",4,@"캐릭이름",@"캐릭터 로그인 테스트"),
        new(@"charm",4,@"부적아이디",@"부적 추가 강제"),
        new(@"charout",4,@"캐릭이름",@"캐릭터 로그아웃 테스트"),
        new(@"check_guildname",4,@"길드이름",@"길드명 중복체크"),
        new(@"checkcell",4,@"",@"셀 확인 (서버용)"),
        new(@"cl_reset",4,@"",@"전투 로그 툴 리셋"),
        new(@"clear_achievement",4,@"",@"업적 초기화"),
        new(@"clear_aggro",4,@"",@"어그로 삭제"),
        new(@"clear_all_achievement",4,@"",@"모든 업적 초기화"),
        new(@"clear_all_crest",4,@"[문장포인트]",@"문장 적용 해제 및 문장 포인트 적용. 인자 없으면 문장 적용 해제만"),
        new(@"clear_all_social",4,@"",@"습득한 모든 Social 삭제"),
        new(@"clear_bonfire",4,@"[거리]",@"유저가 만든 모닥불 삭제"),
        new(@"clear_build_object",4,@"[거리]",@"유저가 만든 빌드 오브젝트 삭제"),
        new(@"clear_cont",4,@"채널 청소",@"채널 청소"),
        new(@"clear_daily_quest_complete",4,@"",@"일일퀘스트 완료 기록 클리어"),
        new(@"clear_drevent",4,@"",@"미숙련 던전매칭 이벤트를 데이터시트로 추가"),
        new(@"clear_dungeonwork",4,@"",@"던전 과제 초기화"),
        new(@"clear_guild_skill",4,@"",@"습득한 모든 길드 스킬 삭제"),
        new(@"clear_quest",4,@"[questId] [all]",@"퀘스트 DB클리어하기"),
        new(@"clear_recipe_world",4,@"",@"worldServer에서 RECIPE 삭제"),
        new(@"clear_seren_guide",4,@"",@""),
        new(@"clear_withdrawer",4,@"",@"겁쟁이 상태 해제"),
        new(@"clearallabnormality",4,@"",@"버프 다 지우기(유료화버프도 비활성화 시키지 않고 다 지운다."),
        new(@"clearbuff",4,@"",@"버프류 모두 삭제"),
        new(@"clearcool",4,@"",@"스킬쿨타임 모두 초기화"),
        new(@"clearfieldpoint",4,@"",@"필드점수 초기화"),
        new(@"clearfp",4,@"",@"필드점수 초기화"),
        new(@"clearware",4,@"창고청소",@"창고청소"),
        new(@"combatlog",4,@"[on/off]",@"전투 로그 활성화"),
        new(@"combatwork",4,@"[combat Work Id]",@"선택된 대상 Npc의 combat 상태 work ID 를 강제로 실행"),
        new(@"complete_all_quest",4,@"",@"모든 자동 수주 퀘스트 완료"),
        new(@"crash",4,@"[파일명]",@"크래시"),
        new(@"create_channel",4,@"월드",@"채널 생성"),
        new(@"crest",4,@"[문장포인트]",@"문장 적용 해제 및 문장 포인트 적용. 인자 없으면 문장 적용 해제만"),
        new(@"crest_all",4,@"",@"문장 모두 습득"),
        new(@"crest_window",4,@"",@"문장 창 열기"),
        new(@"critical",4,@"on/off",@"크리티컬 on/off"),
        new(@"cube_prob",4,@"tid",@"큐브 아이템 확률 정보 보기"),
        new(@"damage",4,@"",@"주위 몬스터에게 데미지 주기"),
        new(@"debugsend",4,@"[on/off]",@"디버그 정보 보내기"),
        new(@"despawn_tbagroup",4,@"[테레토리 ID]",@"신규모드 전장 내 테레토리 디스폰"),
        new(@"despawn_territory",4,@"[사냥터id] [TerritoryId] [채널id]",@"테리토리안에 있는거 전부 디스폰"),
        new(@"despawn_worldspawn",4,@"[WorldSpawnId]",@"WorldSpawnData.xml에서 id가 WorldSpawnId인 WorldSpawn에 속한 모든 스폰 테리토리를 디스폰시키고, 해당 월드스폰은 서버가 재실행했을 때처럼 처음부터 동작한다."),
        new(@"despawnalleventnpc",4,@"",@"모든 event npc 디스폰"),
        new(@"despawnallnpc",4,@"",@"모든 npc 디스폰"),
        new(@"destroy_channel",4,@"월드 채널인스턴스",@"채널 삭제"),
        new(@"destroy_guild",4,@"",@"길드 해체"),
        new(@"disable_citywar_enter_limit",4,@"",@"길드 대전 입장 제한 조건 해제(무조건 입장 가능)"),
        new(@"disable_license",4,@"[라이센스 이름]",@"라이센스 해제"),
        new(@"disconn_all_arbiter",4,@"",@"모든 아비터 서버 세션 끊어버리기"),
        new(@"dont_ban_battle_field",4,@"",@"베틀 필드에서 팅김 방지"),
        new(@"dr_available_count",4,@"",@"검은 틈 퀘스트 수주량 조절"),
        new(@"dr_balancing_usercount",4,@"[userCount]",@"현 위치의 검은 틈의 BalancingUserCount 수정"),
        new(@"dr_close",4,@"[hzid] [dr_tid]",@"검은 틈 닫기"),
        new(@"dr_expand",4,@"",@"현 위치의 검은 틈을 강제로 확장"),
        new(@"dr_fold",4,@"",@"현 위치의 검은 틈을 강제로 수축"),
        new(@"dr_goto",4,@"[hzid] [dr_tid]",@"검은 틈으로 이동"),
        new(@"dr_here",4,@"",@"검은 틈을 유저 위치에 소환"),
        new(@"dr_inspect",4,@"",@"현재 위치의 검은 틈 정보 출력"),
        new(@"dr_list_reserve",4,@"",@"예약된 검은 틈 EventGroup 정보 조회"),
        new(@"dr_open",4,@"[hzid] [dr_tid]",@"검은 틈 열기"),
        new(@"dr_open_group",4,@"[egid]",@"검은 틈 EventGroup 을 강제로 열기"),
        new(@"dr_report",4,@"",@"열려있는 검은 틈 전체 정보 출력"),
        new(@"dr_rereserve_group",4,@"",@"검은 틈 EventGroup 예약 정보를 초기화하고 다시 예약하기"),
        new(@"dr_rightnow",4,@"",@"모든 검은 틈의 Countdown 을 무시하고 바로 시작"),
        new(@"dr_set_abnormality",4,@"[abnormalityId]",@"모든 검은 틈의 이상상태를 고정"),
        new(@"dr_set_npcgroup",4,@"[step] [groupTemplateId]",@"모든 검은 틈의 n 단계 Spawn Npc 고정"),
        new(@"dr_set_questtemplate",4,@"[id1] [id2] [id3]",@"모든 검은 틈의 퀘스트 TemplateId 를 고정"),
        new(@"dr_spawnreport",4,@"",@"검은 틈 소환 대기 목록을 출력"),
        new(@"dr_start_quest",4,@"",@"검은 틈 퀘스트 시작"),
        new(@"dr_step",4,@"[step]",@"검은 틈 단계를 넘김"),
        new(@"dr_time",4,@"[sec]",@"검은 틈 디펜스 시간 조정"),
        new(@"dr_user_count",4,@"",@"검은 틈 퀘스트 진행인원 변경"),
        new(@"drop_all_items",4,@"[on/off]",@"npc를 죽이면 모든 아이템 드롭"),
        new(@"dropitem",4,@"template_id amount",@"아이템 드랍 시키기"),
        new(@"dump_performance_data",4,@"",@""),
        new(@"dungeon_flag",4,@"[flag-name]",@"던전 플래그를 설정"),
        new(@"dungeon_timer",4,@"[timer-value]",@"던전 타이머를 설정"),
        new(@"enable_citywar_enter_limit",4,@"",@"길드ㅐ전 입장 제한 조건 사용"),
        new(@"enable_license",4,@"[라이센스 이름]",@"라이센스 취득"),
        new(@"enable_ride_vehicle",4,@"[on/off]",@"탑승병기 무조건 탑승 가능"),
        new(@"enchantitemsuccess",4,@"[-1 : 항상 실패, 0 : 기본 상태, 1 : 항상 성공]",@"아이템 강화할때 항상 성공되게 할건지"),
        new(@"end_citywar",4,@"",@"공방전 종료"),
        new(@"end_gmevent",4,@"gmEventId channelId",@"GM이벤트 종료 (보상 지급)"),
        new(@"end_npc_arena",4,@"",@"Npc투기장 종료"),
        new(@"endfe",4,@"[contId(all=전체)] [eventId(0=cont전체)]",@"필드이벤트 종료"),
        new(@"endfieldevent",4,@"[contId(all=전체)] [eventId(0=cont전체)]",@"필드이벤트 종료"),
        new(@"enter_dungeon",4,@"[contId] [enter-index]",@""),
        new(@"enter_dungeon_party",4,@"[contId] [enter-index]",@"(같은월드에 있는 파티원 모두 같이)던전 입장"),
        new(@"enter_dungeonwork",4,@"[dungeonId] [randomMode] [workid]",@"과제 선택형 솔로던전 입장"),
        new(@"enter_gmevent",4,@"gmEventId",@"GM이벤트 입장"),
        new(@"epexp_allrev",4,@"on/off",@"모든 보정치 OnOff"),
        new(@"epexp_defaultrev",4,@"on/off",@"기본 보정치 OnOff"),
        new(@"epexp_extrabonus",4,@"on/off",@"기타 보정치 OnOff"),
        new(@"epexp_tsrev",4,@"on/off",@"TS 보정치 OnOff"),
        new(@"exitclear_cool",4,@"[1/0]",@"1이면 비상탈출 시간 무시하고 항상 바로 가능 0이면 보통때 처럼"),
        new(@"expdiv",4,@"[EXP를 나눌 값]",@"경험치 값을 파라미터 값으로 나누어서 획득"),
        new(@"extend_party",4,@"[partyToRaid]",@"파티 ↔ 레이드 변경"),
        new(@"extractitemfail",4,@"[1이면 항상 실패 0이면 원래대로]",@"아이템 추출할때 항상 실패되게 할건지"),
        new(@"extractitemsuccess",4,@"[1이면 항상 성공 0이면 원래대로]",@"아이템 추출할때 항상 성공되게 할건지"),
        new(@"fail_quest",4,@"",@"퀘스트 실패처리"),
        new(@"fast_box",4,@"",@"가챠 및 eventSeed 애니메이션 스킵"),
        new(@"fast_cube",4,@"on / off",@"큐브 재료 없이 열기"),
        new(@"ferotation",4,@"[on/off]",@"필드 이벤트 로테이션 켜고 끄기"),
        new(@"festival_end",4,@"[festivalId]",@"축제 비활성화"),
        new(@"festival_start",4,@"[festivalId]",@"축제 활성화"),
        new(@"fight_npc_arena",4,@"",@"Npc투기장 전투 시작"),
        new(@"finish_battle_field",4,@"[win/lose]",@"강제로 전장 끝내기"),
        new(@"finish_battle_field_round",4,@"",@"라운드 종료"),
        new(@"finish_tutorial",4,@"",@"튜토리얼 종료"),
        new(@"flyspeed",4,@"값",@"비행속도 조정"),
        new(@"force_change_user_status",4,@"[on/off] [userStatus/1=전투/0=일반/2=평화(옛 모닥불)]",@""),
        new(@"force_do_ep_passive",4,@"on/off",@"특성 패시브 100% 발동 on/off"),
        new(@"force_load_topo",4,@"[username]",@"해당 유저에게 강제로 SendLoadTopo"),
        new(@"forever_hero_select",4,@"",@"진행 중인 영웅 선택 과정을 영원히 지속"),
        new(@"forget_guild_skill",4,@"[skillTemplateId] [isActive]",@"길드 스킬 삭제"),
        new(@"forget_social",4,@"[socialMotionId]",@"Social 삭제"),
        new(@"free_flight",4,@"on/off",@"비행에너지 안쓰고 비행할지 온오프"),
        new(@"freeze_condition",4,@"",@"컨디션 수치 고정"),
        new(@"fulldump",4,@"[파일명]",@"풀덤프"),
        new(@"gamble_test",4,@"",@"도박 테스트"),
        new(@"get",4,@"key [id/name]",@"프로퍼티 값 얻어오기"),
        new(@"get_quest",4,@"개수",@"퀘스트 와장창 받기"),
        new(@"get_return_user_reward",4,@"",@"복귀유저 보상받기"),
        new(@"get_rune",4,@"[RuneId] [Amount]",@"룬 획득(보관함)"),
        new(@"ghost",4,@"[on] or [off]",@"주위 스폰된 녀석들의 Server 좌표를 얻어옴"),
        new(@"give_achievement",1,@"",@""),
        new(@"giveup_promotion",4,@"",@"승급 시험 포기"),
        new(@"gopos",4,@"[x] [y] [z]",@"특정 위치로 이동"),
        new(@"goto",4,@"[다른 캐릭터 이름]",@"다른 캐릭터에게로 텔레포트"),
        new(@"goto_battle_field_round",4,@"",@"특정라운드로부터 시작"),
        new(@"goto_least_entered_fe",4,@"[onlyEmpty=1]",@"사람이 가장 적은 이벤트로 이동"),
        new(@"gotofe",4,@"[contId] [eventId]",@"해당 필드이벤트의 시작위치로 이동"),
        new(@"guild_ware_range",4,@"[startIndex] [endIndex] [itemDbId]",@"길드 창고에 아이템 생성"),
        new(@"guildwar_accept",4,@"[상대 길드 이름]",@"싸우자! XXX 길드"),
        new(@"guildwar_giveup",4,@"[상대 길드 이름]",@"항ㅋ 벅ㅋ"),
        new(@"guildwar_raise",4,@"[상대 길드 이름] [추가 베팅 전술칩]",@"싸우자! XXX 길드"),
        new(@"guildwar_start",4,@"[상대 길드 이름] [베팅 전술칩]",@"싸우자! XXX 길드"),
        new(@"hero",4,@"[HeroTemplateId] [HeroSkinId]",@"신규모드 영웅 교체"),
        new(@"holdabnormality_clear",4,@"",@"보관된 버프 다 지우기"),
        new(@"iamtheflashman",1,@"",@""),
        new(@"icanseedeadpeople",1,@"",@""),
        new(@"idle_social_stop",4,@"idle 소셜 정지/시작",@""),
        new(@"ignoreskilllos",4,@"[on/off]",@"스킬 타격시 los체크 여부"),
        new(@"increaseinvensize",4,@"[최소 48에서 88까지]",@"캐릭인벤토리 크기 늘이기 증가만 된다"),
        new(@"insert_item",4,@"templateId itemCount",@"아이템 획득"),
        new(@"insert_Tcat_Product_Sale",4,@"[아이템 ID] [할인 가격], [시간(분)]",@""),
        new(@"interest",4,@"[on 거리] or [off]",@"주위 녀석의 디버그 정보를 수집"),
        new(@"invincible",4,@"[on/off]",@"무적상태"),
        new(@"invisible",4,@"[on/off]",@"NPC가 쌩까는 상태"),
        new(@"invite_guild",4,@"캐릭명",@"길드원 초대"),
        new(@"is_tutorial_user",4,@"",@"튜토리얼 유저인지 확인"),
        new(@"item_add",4,@"[userName] [itemTemplateId] [amount]",@"아이템 추가"),
        new(@"item_del",4,@"[userName] [itemTemplateId] [amount]",@"아이템 삭제"),
        new(@"item_list",4,@"[userName]",@"아이템 리스팅"),
        new(@"item_multidel",4,@"",@""),
        new(@"item_trade",4,@"",@""),
        new(@"itisagooddaytodie",1,@"",@""),
        new(@"iwanttomove",1,@"",@""),
        new(@"join_party",4,@"[planetId] [userDbId]",@"파티 추가"),
        new(@"jump_task",4,@"[questId] [taskId]",@"퀘스트의 특정 Task로 Jump"),
        new(@"jumpto",4,@"[huntingZoneId] [templateId]",@"Npc에게 텔레포트"),
        new(@"kick_party",4,@"[planetId] [userDbId]",@"파티 강퇴"),
        new(@"kill",4,@"범위UU",@"반경내 NPC 사살"),
        new(@"kill_mypet",4,@"",@"펫 소멸시키기"),
        new(@"kill_summonee",4,@"캐릭명",@"길드원 초대"),
        new(@"killme",4,@"",@"자살"),
        new(@"killme2",4,@"",@"크리스탈 부시면서 자살"),
        new(@"learn_all_epperk",4,@"",@"모든 epPerk배우기"),
        new(@"learn_epperk",4,@"[skillId] [level]",@"Ep Perk(특성,효과) 배우기"),
        new(@"learn_guild_skill",4,@"[skillTemplateId] [isActive]",@"길드스킬습득"),
        new(@"learn_recommended_ep",4,@"",@"각 클래스의 추천 특성 적용"),
        new(@"learn_skill",4,@"skillTemplateId isActive",@""),
        new(@"learn_social",4,@"[socialMotionId]",@"Social 습득"),
        new(@"leave_dungeon_party",4,@"",@"(같은월드에 있는 파티원 모두 같이)던전 퇴장"),
        new(@"leave_party",4,@"",@"파티 탈퇴"),
        new(@"level",4,@"새로운레벨",@"레벨 변경"),
        new(@"limited_drop_reset_point",4,@"[gauge id]",@"수량제어 드랍 포인트 리셋"),
        new(@"limited_drop_set_point",4,@"[gauge id] [capacity point]",@"수량제어 드랍 포인트 조절"),
        new(@"list",4,@"key [id/name]",@"프로퍼티 리스팅"),
        new(@"load_drevent",4,@"",@"미숙련 던전매칭 이벤트를 데이터시트로 추가"),
        new(@"login",4,@"[클래스] [마리수]",@"로그인 테스트"),
        new(@"lootitem",4,@"[획득반경]",@"획득반경 내 아이템 루팅, (range > 0: 범위만큼 루팅, range <= 0: 루팅안함, range 생략: 500 만큼 루팅)"),
        new(@"make_me_second",4,@"",@"자신을 세컨캐릭터로 변경"),
        new(@"make_party",4,@"[대상 유저이름]",@"파티 구성"),
        new(@"make_party2",4,@"[대상 유저DbId]",@"파티 구성"),
        new(@"make_vehicle_skill_book",4,@"",@"탑승 스킬북 얻기"),
        new(@"makeitem",4,@"[템플릿ID] [수량] [강화] [명품(1)/각성(2)]",@"아이템 만들기"),
        new(@"makeitem_damage",4,@"[템플릿ID] [강화] [수량]",@"손상된 장비를 생성"),
        new(@"makeitem_op",4,@"[템플릿ID] [수량] [강화] [명품(1)/각성(2)]",@"옵션 레벨이 높게 아이템 만들기"),
        new(@"makeitem_range",4,@"[tid_start] [tid_end] [수량]",@"아이템 여러가지 만들기"),
        new(@"makeitems",4,@"[템플릿ID] [템플릿ID] [템플릿ID] .... [수량]",@"아이템 여러가지 만들기"),
        new(@"makematerial",4,@"[제작아이템id] [개수]",@"제작 아이템 재료 생성"),
        new(@"makemoney",4,@"[amount]",@"돈 만들기"),
        new(@"makeplaytestitem",4,@"[위상] [강화 수치]",@"한 번에 장비 셋팅"),
        new(@"maketestitem",4,@"[enchant]",@"테스트 장비 아이템 생성"),
        new(@"match_battle_field",4,@"",@"강제로 두 파티를 전장에 매칭 [전장TID] [상대아이디]"),
        new(@"memstat",4,@"",@""),
        new(@"merge_item",4,@"fromInvenPos toInvenPos",@"아이템 머지하기"),
        new(@"minigame_skip",4,@"[true/false]",@"낚시 미니게임 스킵"),
        new(@"move_to_village",4,@"",@"사망시 가까운 무덤 이동"),
        new(@"mpfull",4,@"[on/off]",@"MP 만땅 모드"),
        new(@"msg_dungeon",4,@"",@"StrSheet_MonsterBehavior.xml 의 메세지 출력"),
        new(@"msg_monsterbehavior",4,@"[MonsterBehaviorId] [range(1000)]",@"StrSheet_MonsterBehavior.xml 의 메세지 출력"),
        new(@"msg_system",4,@"[readableId]",@"StrSheet_SystemMessage.xml 의 메세지 출력"),
        new(@"next_quiz",4,@"point",@"OX퀴즈 다음문제 진행"),
        new(@"next_repequiz",4,@"point",@"OX퀴즈 패자부활 진행"),
        new(@"next_task",4,@"[questId]",@"다음 Task진행"),
        new(@"nocool",4,@"[on/off]",@"스킬 쿨타임 무한모드"),
        new(@"nodie",4,@"[on/off]",@"피격당하지만 안죽게"),
        new(@"nomod",4,@"[on/off]",@"스킬중 위치보정 끄기모드"),
        new(@"nonpk_list",4,@"",@"이 월드 내에 NonPk 로 설정된 Section 목록 조회"),
        new(@"nonrecovery_actpoint",4,@"[on/off]",@"모험의 주화 자연 회복 적용"),
        new(@"nonrecovery_hp",4,@"[on/off]",@"HP자동회복 on/off"),
        new(@"nonrecovery_mp",4,@"[on/off]",@"MP자동회복 on/off"),
        new(@"nonrecovery_st",4,@"[on/off]",@"ST자동회복 on/off"),
        new(@"notify",1,@"",@""),
        new(@"open_all_box",4,@"",@"인벤토리 내 모든 EventSeed & Gacha 열기"),
        new(@"open_bfstore",4,@"[상점 메뉴 ID]",@"npc 없이 상점 열기"),
        new(@"packettest",4,@"",@""),
        new(@"parcel_fee",4,@"",@"소포 수수료 지불"),
        new(@"parcel_recv",4,@"",@"소포 받기"),
        new(@"parcel_return",4,@"",@"소포 반송"),
        new(@"parcel_send",4,@"",@"소포 보내기"),
        new(@"passive_off",4,@"패시브아이디",@"패시브상태 끄기"),
        new(@"passive_on",4,@"패시브아이디",@"패시브상태 켜기"),
        new(@"passive_see",4,@"",@"패시브상태 화면에 출력"),
        new(@"passive_show",4,@"패시브아이디",@"패시브상태 끄기"),
        new(@"pausenpc",4,@"range",@"NPC 멈추기"),
        new(@"pegasus",4,@"pegasusId",@"페가수스"),
        new(@"perfect_level",4,@"새로운레벨",@"레벨 변경+스킬습득"),
        new(@"perfect_skillPolishing",4,@"",@"모든 스킬 연마 활성화"),
        new(@"petevolution_success",4,@"",@"[-1 = 강제 실패, 0 = 노말, 1 = 강제 성공]"),
        new(@"petmix_success",4,@"",@"[-1 = 강제 실패, 0 = 노말, 1 = 강제 성공]"),
        new(@"pkmodeoff",4,@"",@"PK 상태 강제 해제"),
        new(@"pkmodeOn",4,@"",@"PK"),
        new(@"playtimereward",4,@"[daily/total] [보상ID]",@"누적 접속시간 보상 지급"),
        new(@"prisoner",4,@"[on/off]",@"감옥상태 세팅"),
        new(@"producefatiguepoint",4,@"",@"생산력 셋팅"),
        new(@"produceitemfail",4,@"[1이면 항상 실패 0이면 원래대로]",@"아이템 제작할때 항상 실패되게 할건지"),
        new(@"prof_bug",4,@"새로운숙련도",@"곤충 채집 숙련도 변경"),
        new(@"prof_energy",4,@"새로운숙련도",@"기운 채집 숙련도 변경"),
        new(@"prof_herb",4,@"새로운숙련도",@"약초 채집 숙련도 변경"),
        new(@"prof_mineral",4,@"새로운숙련도",@"광물 채집 숙련도 변경"),
        new(@"profile_world",4,@"",@"월드서버 프로파일링"),
        new(@"proxy_test",4,@"[번호]",@"주어진 번호의 프록시 테스트"),
        new(@"pullmonster",4,@"",@"몬스터를 내 위치로 땡겨오기"),
        new(@"qatest_world",4,@"on/off",@""),
        new(@"randomfe",4,@"",@"함수내에서 지정한 로테이션에서 랜덤하게 1개의 이벤트씩을 시작"),
        new(@"rank_add_point",4,@"[point]",@"기록 경쟁 인던 포인트 추가"),
        new(@"rank_add_private_point",4,@"[point]",@"기록 경쟁 인던 개인 포인트 추가"),
        new(@"rank_add_record",4,@"",@"기록 경쟁 인던 record 1~10000점 랜덤 추가"),
        new(@"rank_clear",4,@"",@"기록 경쟁 인던 클리어"),
        new(@"rank_log",4,@"[on/off]",@"기록 경쟁 인던 클리어"),
        new(@"rank_start",4,@"",@"기록 경쟁 인던 점수 카운트 시작"),
        new(@"rank_test",4,@"",@"기록 경쟁 리코드 막 생성"),
        new(@"ranktimer",4,@"",@"랭크 타이머 진행 시간 출력"),
        new(@"ranktimer_reset",4,@"",@"랭크 타이머 기록 초기화"),
        new(@"ranktimer_state",4,@"[on/off]",@"랭크타이머 시작 종료 메시지 출력여부"),
        new(@"re",4,@"",@"제자리부활"),
        new(@"reaction",4,@"[리액션모션번호]",@"리액션 강제 발생"),
        new(@"recalc_stat",4,@"",@"스탯 재계산"),
        new(@"recv_all_parcel",4,@"",@"모든 우편 수령(서버팀 테스트용)"),
        new(@"recv_daily_bonus",4,@"",@"발키온 지령서 일일 보너스 강제로 수령"),
        new(@"recv_weekly_bonus",4,@"",@"발키온 지령서 주간 보너스 강제로 수령"),
        new(@"refresh_quest",4,@"",@"퀘스트 DB로부터 다시 받아오기"),
        new(@"register_card",4,@"[cardTemplateId] [amount]",@"카드 등록"),
        new(@"registerParts",4,@"",@""),
        new(@"reload_critical_adjust_datasheet",4,@"",@"critical adjust datasheet reload"),
        new(@"reload_datasheet_world",4,@"",@"데이터시트를 모두 리로드"),
        new(@"reload_dr",4,@"",@"검은 틈 데이터시트 리로드"),
        new(@"reload_dungeon",4,@"[던전ID] [DungeonRetry 리로드 여부]",@"지정 던전만 리로드"),
        new(@"reload_flying",4,@"",@"비행 관련 리로드"),
        new(@"reload_herodata",4,@"",@"신규모드 데이터시트 리로드"),
        new(@"reload_huntingzone",4,@"[헌팅존ID]",@"지정 헌팅존만 리로드"),
        new(@"reload_item",4,@"",@"ItemTemplate 리로드"),
        new(@"reload_limited_drop_datasheet",4,@"",@"limited drop data sheet reload"),
        new(@"reload_masstige_datasheet",4,@"",@"masstige datasheet reload"),
        new(@"reload_quest",4,@"",@"퀘스트 데이타 시트를 모두 리로드"),
        new(@"reload_rank",4,@"[id]",@"기록 경쟁 인던 데이터 xml 리로드"),
        new(@"reload_token_exchange_datasheet",4,@"",@"token exchange data sheet reload"),
        new(@"reload_userskill",4,@"",@"유저 스킬 다시 읽기"),
        new(@"remove_guildtower",4,@"",@"길드 타워 제거"),
        new(@"remove_target_guildtower",4,@"",@""),
        new(@"reputation_time_init",4,@"[npcGuildId]",@"평판제한 시간 리셋 "),
        new(@"reset_add_compensation_count",4,@"",@"이벤트 매칭 TASK 추가 보상을 모두 받지 않은 것으로 리셋"),
        new(@"reset_all_phaselevel_world",4,@"",@"모든 유저의 던전 페이즈 정보 초기화(월드)"),
        new(@"reset_all_user_vip_store",4,@"",@""),
        new(@"reset_attendance",4,@"",@"출석체크 리셋"),
        new(@"reset_daily_epexp",4,@"",@"일일 획득 경험치 초기화"),
        new(@"reset_daily_event_quest",4,@"",@"일일 플레이 가이드 이벤트 리셋"),
        new(@"reset_daily_quest",4,@"",@"일일퀘스트 시드 재설정"),
        new(@"reset_delivery_list",4,@"",@"납품 리스트 리셋"),
        new(@"reset_dungeon_clearcount",4,@"",@""),
        new(@"reset_dungeon_enter_count",4,@"",@"던전 입장횟수 기록 삭제"),
        new(@"reset_dungeonhistory",4,@"",@"모든 던전 쿨타임 리셋"),
        new(@"reset_ep",4,@"",@"Ep 시스템 초기화"),
        new(@"reset_epperk",4,@"",@"Ep Perk(특성,효과) 초기화"),
        new(@"reset_masstige_status",4,@"",@"국민강화 목표템 초기화"),
        new(@"reset_profile_world",4,@"",@"리셋 월드서버 프로파일데이타"),
        new(@"resumenpc",4,@"range",@"NPC 다시 플레이"),
        new(@"resurrection",4,@"",@"제자리부활"),
        new(@"rightbaseitem",4,@"[RightID] [ItemTID]",@"RightBaseItem 받기"),
        new(@"rightnow_gmevent",4,@"gmEventId",@"대기중인 GM이벤트 바로 시작"),
        new(@"sealitemnow",4,@"[1이면 바로 0이면 원래대로]",@"아이템 귀속시킬때 바로 귀속되게"),
        new(@"send_ask_code_hash",4,@"",@"코드해시 요청 보내기"),
        new(@"set",4,@"key value [id/name]",@"프로퍼티 값 세팅"),
        new(@"set_achievement_accomplished",4,@"",@"업적 달성시키기"),
        new(@"set_achievement_cond_value",4,@"",@"업적Condition값 설정"),
        new(@"set_add_compensation_count",4,@"[eventId] [acquireNum]",@"이벤트 매칭 TASK 추가 보상 획득 횟수 조작"),
        new(@"set_all_achievement_accomplished",4,@"",@"모든 업적 달성시키기"),
        new(@"set_autowatingtime",4,@"[millisecond]",@"자낚 대기 시간 설정"),
        new(@"set_bitetime",4,@"[millisecond]",@"입질 대기 시간 설정"),
        new(@"set_condition",4,@"value",@"유저의 컨디션수치 설정"),
        new(@"set_custom_string",4,@"",@"[itemDbid] [String] 아이템 커스텀 이름 변경"),
        new(@"set_dlm_delay",4,@"min [max]",@"월드-아비터간 작업 수행 시 랜덤 딜레이 주기 (단위: ms)"),
        new(@"set_dr_clear_each",4,@"[RewardId]",@"시공의 균열 단일 보상 설정"),
        new(@"set_dr_clear_fail",4,@"[RewardId]",@"시공의 균열 실패 보상 설정"),
        new(@"set_dr_clear_general",4,@"[RewardId]",@"시공의 균열 전역 보상 설정"),
        new(@"set_dr_clear_personal",4,@"[RewardId]",@"시공의 균열 개인 보상 설정"),
        new(@"set_dr_hp",4,@"[hpRate]",@"시공의 균열 오브젝트 초기 Hp 비율 설정"),
        new(@"set_dungeon_clear",4,@"",@"던전 클리어 설정"),
        new(@"set_dungeon_reset_time",4,@"",@"던전 입장횟수 삭제 시간 설정"),
        new(@"set_dungeonwork_value",4,@"[hit/combo/timer] [value]",@"시험의던전 과제 값 설정"),
        new(@"set_equipexp",4,@"[숙련도 exp]",@"장비 숙련도 경험치 변경"),
        new(@"set_exp",4,@"[EXP값]",@"경험치 값 세팅"),
        new(@"set_fishing_reward_table",4,@"[tableId]",@"보상 테이블 id 설정"),
        new(@"set_gamble_master",4,@"",@"도신이 되기"),
        new(@"set_gamble_property",4,@"",@"도신 프로퍼티 설정"),
        new(@"set_hurryup_gmevent",4,@"[hurryUpRatio] [hurryUpCounts(csv)]",@"GM이벤트 마감임박 변수설정"),
        new(@"set_login_day",4,@"[period] [loginDay]",@"일일 플레이 가이드 출석 체크"),
        new(@"set_minigamelevel",4,@"[level]",@"미니게임 레벨 설정"),
        new(@"set_money",4,@"[amount]",@" 돈 세팅"),
        new(@"set_npcguild_exp",4,@"[npcGuildId] [grade] [exp]",@"평판 세력 경험치 설정"),
        new(@"set_npcguild_point",4,@"[npcGuildId] [point]",@"평판 포인트 설정"),
        new(@"set_on_dungeon_event",4,@"",@"던전 모든 이벤트 시작"),
        new(@"set_on_field_event",4,@"",@"필드이벤트의 모든 EventGroup 시작"),
        new(@"set_pc_level",4,@"캐릭명 레벨",@"캐릭 레벨 세팅"),
        new(@"set_pc_loc",4,@"캐릭명 위치스트링",@"캐릭 위치 세팅"),
        new(@"set_petdur",4,@"[dur]",@"changing pet-dur temporarily"),
        new(@"set_petprof",4,@"[숙련도]",@"펫 숙련 임의 변경"),
        new(@"set_pkpoint",4,@"[pkPoint]",@"pK포인트 변경"),
        new(@"set_promotion",4,@"",@"승급 달성"),
        new(@"set_round_pve_kill_point",4,@"",@"PveKill_Point[point]"),
        new(@"set_round_pve_skill_point",4,@"",@"PveSkill_Point[point]"),
        new(@"set_skill_prof",4,@"skillId skillProf",@"스킬 숙련도 설정"),
        new(@"set_temper_ratio",4,@"인챈트확률",@"인챈트확률고정"),
        new(@"set_token_exchange_point",4,@"[tokenExchangeId] [point]",@"토큰 점수 조정"),
        new(@"set_tutorial_user",4,@"[on/off]",@"튜토리얼 유저 여부 설정"),
        new(@"set_walk_speed",4,@"",@"걷기 속도 설정"),
        new(@"set_world_worldparam",4,@"[param-name] [param-value]",@"WorldParam 수정"),
        new(@"setfeprogress",4,@"[contId] [eventId] [setvalue]",@"필드이벤트 진행도 설정"),
        new(@"setfieldeventprogress",4,@"[contId] [eventId] [setvalue]",@"필드이벤트 진행도 설정"),
        new(@"setmoney",4,@"[이름] [돈]",@"돈 세팅"),
        new(@"setrestbonus",4,@"rest_bonus",@""),
        new(@"show_bonfire_info",4,@"",@"현재 유저의 모닥불 정보 보여주기"),
        new(@"show_chapter",4,@"",@"집회소 보기"),
        new(@"show_condition",4,@"",@"유저의 컨디션수치 보기"),
        new(@"show_FinalConditionalSkillProb",4,@"",@"파트너 스킬 최종 확률 확인(스킬 발동 후 사용)"),
        new(@"show_incubator",4,@"",@"펫 인큐베이터 열기"),
        new(@"show_items",4,@"[tabIdx] [beginIdx] [endIdx]",@"인벤 item 정보 확인"),
        new(@"show_limited_drop_info",4,@"[gauge id]",@"수량제어 게이지 정보 보여주기"),
        new(@"show_petmanager",4,@"",@"펫 메니저 열기"),
        new(@"show_phaselevel_world",4,@"",@"내 페이즈 정보"),
        new(@"show_skill_learn",4,@"huntingZoneId npcId",@""),
        new(@"show_social_learn",4,@"",@"습득한 Social 보이기"),
        new(@"show_temper_window",4,@"",@"항가~"),
        new(@"show_time",4,@"",@"현재 시간 보기"),
        new(@"show_user_status",4,@"",@"유저의 상태 보기"),
        new(@"show_vs",4,@"",@"탑승병기 속도 출력"),
        new(@"showfei",4,@"[on/off]",@"필드이벤트 상황정보 텍스트 출력"),
        new(@"showfeinfo",4,@"[on/off]",@"필드이벤트 상황정보 텍스트 출력"),
        new(@"showfep",4,@"",@"현재 참여중인 fieldEvent 내부값 보여주기"),
        new(@"showfeprogress",4,@"",@"현재 참여중인 fieldEvent 내부값 보여주기"),
        new(@"showinven",4,@"",@""),
        new(@"showpos",4,@"[x] [y] [z] [showTime]",@"디버깅용 벡터 위치 표시"),
        new(@"shuttle",4,@"[on/off] shuttleId",@"동적지오(셔틀) 키고 끄기"),
        new(@"skill_cheater_world",4,@"[on/off] [termSeconds(int)] [countThreashold(int)] [kick/nokick]",@"스킬 치터 설정변경"),
        new(@"skill_miss_limit",4,@"",@"몬스터가 타겟에게 높이 차이등으로 스킬적중을 몇 회 실패했을 때 리셋할건지"),
        new(@"skillLog",4,@"",@"서버 파일로그 남기기"),
        new(@"skip_hero_select",4,@"",@"진행 중인 영웅 선택 과정 스킵"),
        new(@"sm",4,@"[시스템메시지번호]",@"시스템메시지"),
        new(@"social",4,@"[socialMotionId]",@"소셜"),
        new(@"spawn_bonfire",4,@"typeid",@"모닥불 소환하기"),
        new(@"spawn_territory",4,@"[사냥터Id] [TerritoryId] [채널id]",@"테리토리안에 있는거 전부 스폰"),
        new(@"spawn_worldspawn",4,@"[WorldSpawnId] [SpawnTerritoryGroupId]",@"WorldSpawnData.xml에서 id가 WorldSpawnId인 WorldSpawn의 현재 스폰 테리토리 그룹을 id가 SpawnTerritoryGroupId인 SpawnTerritoryGroup으로 변경한다."),
        new(@"spawnalleventnpc",4,@"",@"모든 event npc 스폰"),
        new(@"spawnallnpc",4,@"",@"모든 npc 스폰"),
        new(@"spawncollection",4,@"",@"유저 채널의 모든 채집물 리스폰"),
        new(@"spawnnpc",4,@"[사냥터Id] [NpcTemplateId] [Count]",@"스폰 시켜보자"),
        new(@"spawnworkobject",4,@"[huntingZoneId] [templateId]",@"Work Object 스폰"),
        new(@"speed",4,@"multiplier",@"이동 속도 증가"),
        new(@"speed_hack_check",4,@"",@"스팩 체크 [on/off]"),
        new(@"start_battle",4,@"",@"전장 즉시 시작"),
        new(@"start_citywar",4,@"",@"공방전 시작"),
        new(@"start_eventgroup",4,@"[id]",@"던전 이벤트그룹 강제 시작"),
        new(@"start_npc_arena",4,@"",@"Npc투기장 시작"),
        new(@"start_promotion",4,@"",@"승급 시험 시작"),
        new(@"start_quest",4,@"퀘스트아이디",@"퀘스트 시작"),
        new(@"start_seren_guide",4,@"[type, id]",@"세렌가이드 시작"),
        new(@"start_tbagroup",4,@"[테레토리 ID]",@"신규모드 전장 내 테레토리 스폰"),
        new(@"startfe",4,@"[contId] [eventId]",@"필드이벤트 시작"),
        new(@"startfieldevent",4,@"[contId] [eventId]",@"필드이벤트 시작"),
        new(@"startnpcskill",4,@"skill_template_id",@"NPC 스킬실행 시키기"),
        new(@"stfull",4,@"[on/off]",@"ST 만땅 모드"),
        new(@"stopFloatingCastleUserCheck",4,@"",@""),
        new(@"store_changeinfo",4,@"[index]",@"상점 아이템 판매 수정 사항 보여주기 (WorldServer)"),
        new(@"stwork",4,@"[combat Work Id]",@"선택된 대상 Npc의 combat 상태 work ID 를 강제로 실행"),
        new(@"style_ware_range",4,@"[startIndex] [endIndex] [itemDbId]",@"스타일 창고에 아이템 생성"),
        new(@"summonParty",4,@"",@"파티원 모두를 내 위치로 소환"),
        new(@"swap_party",4,@"[slotIndex1] [slotIndex2]",@""),
        new(@"sysconfig_world",4,@"",@""),
        new(@"task_goal",4,@"[questId] [taskIdx] [flag]",@""),
        new(@"tba_account_level",4,@"[레벨]",@"신규모드 계정 레벨"),
        new(@"tba_add_account_exp",4,@"[경험치]",@"신규모드 계정 경험치 추가"),
        new(@"tba_change_kda",4,@"[k,d,a]",@"신규모드 전장 KDA 수정 (델타 값 아님)"),
        new(@"tba_grade_reward",4,@"리워드 테스트용도",@""),
        new(@"tba_update_battlefield_daily_reward_count",4,@"[newCount]",@"신규모드 전장 일일보상제한횟수 변경"),
        new(@"teleport",4,@"[worldId] [x] [y] [z]",@"텔레토비"),
        new(@"teleport_channel",4,@"",@""),
        new(@"temper_item",4,@"temperItemSlot materialItemSlot",@"아이템 제련"),
        new(@"test_parts_store",4,@"",@""),
        new(@"testoff",4,@"",@"프로그램테스트 종료"),
        new(@"teston",4,@"테스트종류, 기타인자",@"프로그램테스트 시작"),
        new(@"this",4,@"",@"내 계정의 캐릭터들의 위치를 지금 캐릭터 위치로 강제 조작해준다"),
        new(@"toggle_epInfo",4,@"",@"특성 Info"),
        new(@"track_dynamic",4,@"",@"현재 타겟으로 잡혀 있는 Npc 하나 만 추적 리스트에서 트랙킹"),
        new(@"track_target",4,@"",@"선택된 대상 Npc를 추적 리스트에 추가"),
        new(@"trade_accept",4,@"",@""),
        new(@"trade_additem",4,@"",@""),
        new(@"trade_request",4,@"",@""),
        new(@"unidentifysuccess",4,@"",@"재봉인 무조건 성공[on/off]"),
        new(@"unRegisterParts",4,@"",@""),
        new(@"untrack_target",4,@"",@"선택된 대상 Npc를 추적 리스트에서 제거"),
        new(@"update_battlepass_mission_count",4,@"[MissionKind] [Count]",@"배틀패스 미션 카운트 추가"),
        new(@"use_exp_gain_data",4,@"[on/off]",@""),
        new(@"userawake",4,@"[grade]",@"[0 = 미각성 1 = 각성"),
        new(@"vaporize",4,@"",@"진정한 투명화"),
        new(@"vehicle_avatar",4,@"[huntingZoneId] [templateId]",@"쿠마스(avatar) 탑승"),
        new(@"vehicle_clear_cooltime",4,@"",@"탑승병기 스킬 쿨타임 초기화"),
        new(@"vehicle_dettach",4,@"",@"쿠마스/탱크 강제 하차"),
        new(@"vehicle_killself",4,@"",@"탑승병기 자폭"),
        new(@"vehicle_nocool",4,@"[on/off]",@"탑승병기 스킬 쿨타임 없애기"),
        new(@"view_channel",4,@"",@"채널 보기"),
        new(@"virtual_latency",4,@"[min] [max]",@"가상 레이턴시"),
        new(@"visit_all_sections",4,@"",@"모든지역방문"),
        new(@"vm_buy",4,@"[vm인벤#,개수] [...]",@"구매"),
        new(@"vm_edit_buy",4,@"[vm인벤#,유저인벤#,tempId,살개수,회수할개수,가격] [...]",@"구매기 세팅"),
        new(@"vm_edit_sell",4,@"[회수금액] [vm인벤#,유저인벤#,tempId,팔개수,회수할개수,가격] [...]",@"판매기 세팅"),
        new(@"vm_sell",4,@"[vm인벤#,개수] [...]",@"판매"),
        new(@"vm_show_buy",4,@"",@"구매목록보기"),
        new(@"vm_show_sell",4,@"",@"판매목록보기"),
        new(@"ware_list",4,@"",@"창고 보기"),
        new(@"ware_range",4,@"[startIndex] [endIndex] [itemDbId]",@"계정 창고에 아이템 생성"),
        new(@"whereis",1,@"",@""),
        new(@"win_battle_field",4,@"",@"강제로 전장에서 승리"),
        new(@"write_gcfunctions",4,@"",@""),
        new(@"부활",4,@"",@"제자리부활"),
    };

    /// <summary>Rows whose name, arguments or description contain <paramref name="keyword"/>.</summary>
    public static IEnumerable<Entry> Search(string keyword)
    {
        keyword ??= string.Empty;
        foreach (var row in Rows)
            if (keyword.Length == 0
                || row.Name.Contains(keyword, StringComparison.OrdinalIgnoreCase)
                || row.Arguments.Contains(keyword, StringComparison.Ordinal)
                || row.Description.Contains(keyword, StringComparison.Ordinal))
                yield return row;
    }
}
